import.os
os.system(clear)
import.time                                                                                                                                                         ,,                     
print("`7MMF'     A     `7MF'`7MMmmmYp,                                 db               mm")
time.sleep(0.1)
print("  `MA     ,MA     ,V    MM    Yb                                                  MM")
time.sleep(0.1)
print("   VM:   ,VVM:   ,V     MM    dP     ,pP"Ybd  ,p6"bo  `7Mb,od8 `7MM  `7MMpdMAo. mmMMmm")
time.sleep(0.1)
print("    MM.  M' MM.  M'     MM"""bg.     8I   `" 6M'  OO    MM' "'   MM    MM   `Wb   MM")
time.sleep(0.1)
print("    `MM A'  `MM A'      MM    `Y     `YMMMa. 8M         MM       MM    MM    M8   MM")
time.sleep(0.1)
print("     :MM;    :MM;       MM    ,9     L.   I8 YM.    ,   MM       MM    MM   ,AP   MM")
time.sleep(0.1)
print("      VF      VF      .JMMmmmd9      M9mmmP'  YMbmd'  .JMML.   .JMML.  MMbmmd'    `Mbmo")
time.sleep(0.1)
print("                                                                       MM")
time.sleep(0.1)
print("                                                                     .JMML.")
time.sleep(0.1)
login = imput("Login:")
time.sleep(1.0)
print("Seu nome é" , login , ",certo?"
time.sleep("1.0")
print("Cadastrado com sucesso")
